package com.cybertek.tests.day21_db_testing;

public class sqlRules {
}
/*CONNECT TO VYTRACK:
GO TO GOOGLE, DOWNLOAD mysql-connector-java-8.0.28 (OR OTHER VERSION)
IN SQL DEVELOPER GO TO TOOLS -> PREFERENCES -> DATABASE -> 3RD PATY JDBC DRIVER -> ADD ENTRY -> SELECT: mysql-connector-java-8.0.28
CREATE NEW CONNECTION IN SQL DEVELOPER
ENTER ANY CONNECTION NAME
USERNAME: qa_user
PASSWORD: qa_user
CONNECTION TYPE: mysql
HOST: 107:23:27:171 (CYBERTEK HOST, NOT jAVID'S)
CLICK ON CHOOSE DATABASE
CLICK ON DROPDOWN AND SELECT bitnami_orocrm
CONNECT/SAVE

now vytrack is connected to sql.
AFTER THIS WHEN USE INTELLIJ FOR VYTRACK AND SQL TOGETHER, WE HAVE ADD ojdbc8 DEPENDENCY (FOR ORACLE)
AND mysql-connector-java DEPENDENCY (MYSQL, FOR ALL WE WROTE ABOVE) TO POM.XML*/